### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by vjau** [mmomtchev/Queue#106]
Thank you for this package.
The example code "running sequentially"  seems incomplete to me. Could you take a look ?
Thanks !

**Comment by mmomtchev** [comment]
By incomplete, you mean the code does not run because it references non-existing functions?

**Comment by vjau** [comment]
I can figure out where `myq` is coming from from the others examples, but i don't know what the `let p` is for nor how this example is fondamentally different from the first example. You named it "Running sequentially", but isn't it the whole point of your package ?
