### ISSUE TITLE
A way to wait indefinitely until a job is completed

### ISSUE THREAD

**Issue by dr-nyt** [mmomtchev/Queue#65]
Hi, this is such an amazing project, thank you!

I wanted to know if there was a way to wait indefinitely until a job is completed before moving to the next in queue? Currently just setting it to a really large number does the job, but it just seems there is probably a better way that I'm missing.

I need this because I use this to write to a file on any state change, and it can result in overwriting issues sometimes if multiple file saves are called at the same time.

Again thank you for an amazing project!

**Comment by mmomtchev** [comment]
You shouldn't be using a timer for this, just the maximum number of concurrent users to 1

**Comment by dr-nyt** [comment]
I feel so dumb right now 🤦‍♂️
