### ISSUE TITLE
TypeError: Queue is not a constructor

### ISSUE THREAD

**Issue by Ritin** [mmomtchev/Queue#67]
while using v2.1.4

const {Queue} = require('async-await-queue');
const myq = new Queue(1, 100);

TypeError: Queue is not a constructor

"typescript": "~4.9.5"
Works with v1.2.1

saw diff in index.d.ts 
in 2.1.4   export declare class Queue ....  is used
in 1.2.1 export class Queue ...  is used
saw Andre Pena's answer. He thinks its of no use
https://stackoverflow.com/questions/35019987/what-does-declare-do-in-export-declare-class-actions

thanks

**Comment by mmomtchev** [comment]
Can you make a repo with a repro for this? It doesn't do it for me. v1 had a handwritten `index.d.ts` but this `.d.ts` has been generated by `tsc`.

**Comment by Ritin** [comment]
Generated a new express app and used v2.1.4
its working.. cannot reproduce
